### ISSUE TITLE
ADE20K

### ISSUE THREAD

**Issue by luodamao** [bubbliiiing/pspnet-pytorch#6]
这是我下载的ade20k数据集，下面是它的文件分布，我能直接把它的标注图像复制到VOC文件夹中进行训练吗？我需要更改类别以及其数量吗？

![ade20k](https://user-images.githubusercontent.com/58473981/111892207-42e26d80-8a34-11eb-9bdd-bc0ff9daea5b.jpg)

**Comment by luodamao** [comment]
博主，把你给的与训练权重加载代码注释后，发现训练效果不大好。。。还有我将你的train.py文件第134行代码net.train()注释掉也能训练。不晓得会产生什么影响

![无标题](https://user-images.githubusercontent.com/58473981/111927043-30c30680-8aea-11eb-87a6-157e3dcb7269.png)

**Comment by bubbliiiing** [comment]
1、你这个格式不太对吧。需要转换一下
2、https://www.bilibili.com/read/cv10239076看一下这个
3、train的话影响bn，不要修改

**Comment by luodamao** [comment]
@bubbliiiing 你发的链接页面被删除了

**Comment by bubbliiiing** [comment]
https://www.bilibili.com/read/cv10239076
